substitutions:
  name: "sonoff-basic"
  friendly_name: "Sonoff Basic"
  project_name: "Taiwan Smart Home.Sonoff Basic Relay"
  project_version: "1.0"
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"
    
esp8266:
  board: esp01_1m    
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:  
  port: 80
  
logger:
api:
ota:  

# Device Specific Config
binary_sensor:
  - platform: gpio
    id: push_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    internal: true
    on_press:
      # Prevents unintended LED lit states.
      if:
        condition:
          - switch.is_off: relay
        then:
          - switch.turn_on: blue_led
          - switch.turn_on: relay
        else:
          - switch.turn_off: relay

switch:
  # The relay switches on the red side of the LED when active.
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    # on_turn_off:
      if:
        condition:
          - switch.is_on: blue_led
        then:
          - switch.turn_off: blue_led
  # With this we can control the blue side of the LED. 
  - platform: gpio
    id: blue_led
    pin:
      number: GPIO13
      inverted: True
  - platform: restart
    name: Sonoff Basic Restart       

sensor:
  - platform: wifi_signal
    name: wifi signal
    update_interval: 600s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    mac_address:
      name: MAC   
    
